sudo: true

services:
  - docker

env:
  global:
    - BAZEL_VERSION=0.8.1

before_install:
  - script/install-bazel

install:
  - bazel info
  - bazel build //:all-targets

script:
  - bazel test --test_output=errors  //...

cache:
  timeout: 300
  directories:
    - $HOME/.vsco/bazel

notifications:
  email: false
  slack: false
