sudo: required
language: go
go: 1.6

branches:
  only:
    - master
install:
  - script/bootstrap
before_script:
  - echo java -version
  - script/startdb
script:
  - script/test
notifications:
  email: false
  slack: false
