sudo: required
language: go
go: 1.6

branches:
  only:
    - master
install:
  - script/bootstrap
  - npm install -g dynalite
script:
  - script/startdb
  - script/test
notifications:
  email: false
  slack: false
